version: "3.9"
services:
  ots_database:
    image: redis:latest
    container_name: ots_database
    ports:
      - "6379:6379"
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 50M
  ots_backend:
    image: ots_backend:latest
    container_name: ots_backend
    build: 
      context: backend/
    ports:
      - "5000:5000"
    environment:
      OTS_SALT: 'somethingIDonotWantToKnow'
      OTS_DB_HOST: ots_database
      OTS_DB_PORT: 6379
      # OTS_DB_PASSWORD: None
      OTS_DB_SSL: "False"
      OTS_DB_NAME: 0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
  ots_frontend:
    image: ots_frontend:latest
    container_name: ots_frontend
    build:
      context: frontend/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_ENV: "dev"