version: "3.9"
services:
  ots_database:
    image: redis:latest
    container_name: ots_database
    ports:
      - "6379:6379"
  ots_backend:
    image: ots_backend:latest
    container_name: ots_backend
    build: 
      context: backend/
    ports:
      - "5000:5000"
    environment:
      OTS_SALT: 'somethingIDonotWantToKnow'
      OTS_DB_HOST: ots_database
      OTS_DB_PORT: 6379
      # OTS_DB_PASSWORD: None
      OTS_DB_SSL: "False"
      OTS_DB_NAME: 0
  ots_frontend:
    image: ots_frontend:latest
    container_name: ots_frontend
    build:
      context: frontend/
    ports:
      - "3000:3000"
    environment:
      # client/user should be able to resolve below REACT_APP_OTS_BACKEND_URL
      # Either update /etc/hosts file to resolve ots_backend=localhost
      # or change address to http://localhost:5000 
      REACT_APP_OTS_BACKEND_URL: "http://localhost:5000"