{{- if .Values.otsBackend.autoscaling.enabled }}
kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Chart.Name }}
  labels:
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  maxReplicas: {{ .Values.otsBackend.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.otsBackend.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: {{ .Chart.Name }}-backend
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Max
      stabilizationWindowSeconds: 60
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min 
      stabilizationWindowSeconds: 300 
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization 
        averageUtilization: {{ .Values.otsBackend.autoscaling.averageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization 
        averageUtilization: {{ .Values.otsBackend.autoscaling.averageUtilization }}
{{- end }}
