apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Chart.Name }}
  labels:
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    app: {{ .Chart.Name }}-backend
  type: {{ .Values.otsBackend.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.otsBackend.service.port }}
      targetPort: 5000
