kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2
metadata:
  name: "{{ .Values.otsNamespace }}-backend"
  namespace: "{{ .Values.otsNamespace }}"
  labels:
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  maxReplicas: {{ .Values.otsBackendHpaMaxReplicas }}
  minReplicas: {{ .Values.otsBackendHpaMinReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: "{{ .Values.otsNamespace }}-backend"
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Max
      stabilizationWindowSeconds: 60
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min 
      stabilizationWindowSeconds: 300 
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization 
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization 
        averageUtilization: 80