apiVersion: v1
kind: Service
metadata:
  name: ots-backend
  namespace: ots
spec:
  selector:
    app: ots-backend
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
