apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}-backend
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  {{- if not .Values.otsBackend.autoscaling.enabled }}
  replicas: {{ .Values.otsBackend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  template:
    metadata:
      {{- with .Values.otsBackend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Chart.Name }}-backend
        {{- range $k, $v := .Values.labels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
    spec:
      {{- with .Values.otsBackend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.otsBackend.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-backend
        securityContext:
          {{- toYaml .Values.otsBackend.securityContext | nindent 12 }}
        image: "{{ .Values.otsBackend.image.repository }}:{{ .Values.otsBackend.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.otsBackend.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
        resources:
          {{- .Values.otsBackend.resources | toYaml | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
          - name: OTS_SALT
            value: {{ .Values.otsBackend.env.OTS_SALT | default "somethingIDonotWantToKnow" | quote }}
          - name: OTS_DB_HOST
            value: {{ .Values.otsBackend.env.OTS_DB_HOST | quote }}
          - name: OTS_DB_PORT
            value: {{ .Values.otsBackend.env.OTS_DB_PORT | default 6379 | quote }}
          - name: OTS_DB_PASSWORD
            {{- if empty .Values.otsBackend.env.OTS_DB_PASSWORD }}
            {{- else }}
            value: {{ .Values.otsBackend.env.OTS_DB_PASSWORD | quote }}
            {{- end }}
          - name: OTS_DB_SSL
            value: {{ .Values.otsBackend.env.OTS_DB_SSL | default "False" | title | quote }}
          - name: OTS_DB_NAME
            value: {{ .Values.otsBackend.env.OTS_DB_NAME | default 0 | quote }}
      {{- with .Values.otsBackend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otsBackend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otsBackend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}