apiVersion: apps/v1
kind: Deployment
metadata:
  name: ots-backend
  namespace: ots
  labels:
    app: ots-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ots-backend
  template:
    metadata:
      labels:
        app: ots-backend
    spec:
      containers:
      - name: ots-backend
        image: ots_backend
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "512m"
          limits:
            memory: "512Mi"
            cpu: "1024m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        - name: OTS_SALT
          value: "somethingIDonotWantToKnow"
        - name: OTS_DB_HOST
          value: "192.168.29.243"
        - name: OTS_DB_PORT
          value: "6379"
        - name: OTS_DB_PASSWORD
          # value: "someRedisPassword"
        - name: OTS_DB_SSL
          value: "False"
        - name: OTS_DB_NAME
          value: "0"
