apiVersion: apps/v1
kind: Deployment
metadata:
  name: ots-frontend
  namespace: ots
  labels:
    app: ots-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ots-frontend
  template:
    metadata:
      labels:
        app: ots-frontend
    spec:
      containers:
      - name: ots-frontend
        image: ots_frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "512m"
          limits:
            memory: "512Mi"
            cpu: "1024m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 45
          periodSeconds: 5
        env:
        - name: REACT_APP_ENV
          value: "prod"
        - name: REACT_APP_OTS_BACKEND_URL
          value: "http://api.ots.com"
