apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.otsNamespace }}-frontend"
  namespace: "{{ .Values.otsNamespace }}"
  labels:
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  rules:
    - host: "{{ .Values.otsFrontendIngressAddress }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.otsNamespace }}-frontend"
                port:
                  number: 3000