apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ots-frontend
  namespace: ots
spec:
  rules:
    - host: ots.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ots-frontend
                port:
                  number: 3000