apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.otsNamespace }}-frontend"
  namespace: "{{ .Values.otsNamespace }}"
  labels:
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    app: "{{ .Values.otsNamespace }}-frontend"
  type: "{{ .Values.otsFrontendServiceType }}"
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000