apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}-frontend
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  {{- if not .Values.otsFrontend.autoscaling.enabled }}
  replicas: {{ .Values.otsFrontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend
  template:
    metadata:
      {{- with .Values.otsFrontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Chart.Name }}-frontend
        {{- range $k, $v := .Values.labels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
    spec:
      {{- with .Values.otsFrontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.otsFrontend.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-frontend
        securityContext:
          {{- toYaml .Values.otsFrontend.securityContext | nindent 12 }}
        image: "{{ .Values.otsFrontend.image.repository }}:{{ .Values.otsFrontend.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.otsFrontend.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources:
          {{- .Values.otsFrontend.resources | toYaml | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 45
          periodSeconds: 5
        env:
        - name: REACT_APP_ENV
          value: {{ .Values.otsFrontend.env.REACT_APP_ENV | default "prod" | quote}}
        - name: REACT_APP_OTS_BACKEND_URL
          value: {{ .Values.otsFrontend.env.REACT_APP_OTS_BACKEND_URL | quote }}
      {{- with .Values.otsFrontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otsFrontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otsFrontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}