apiVersion: v1
kind: Service
metadata:
  name: ots-frontend
  namespace: ots
spec:
  selector:
    app: ots-frontend
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000