apiVersion: apps/v1
kind: Deployment
metadata:
  name: ots-frontend
  namespace: ots
  labels:
    app: ots-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ots-frontend
  template:
    metadata:
      labels:
        app: ots-frontend
    spec:
      containers:
      - name: ots-frontend
        image: ots_frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 3
        env:
        - name: REACT_APP_ENV
          value: "prod"
        - name: REACT_APP_OTS_BACKEND_URL
          value: "https://api.ots.example.com"
